import { createFileRoute } from "@tanstack/react-router";
import { PageHeader } from "@/components/VizPanel";
import { AiTutorPanel } from "@/components/AiTutorPanel";

export const Route = createFileRoute("/tutor")({
  head: () => ({
    meta: [
      { title: "AI Tutor — NeuroVision Lab" },
      {
        name: "description",
        content: "Ask questions about the current visualization and get explanations from the backend AI tutor.",
      },
      { property: "og:title", content: "AI Tutor — NeuroVision Lab" },
      { property: "og:description", content: "A context-aware tutor for convolution, U-Net and nnU-Net questions." },
    ],
  }),
  component: TutorPage,
});

function TutorPage() {
  return (
    <div>
      <PageHeader
        eyebrow="Tools"
        title="AI Tutor"
        description="The tutor receives the module, step and visualization state you are looking at, and answers are generated by the FastAPI backend."
      />
      <div className="panel h-[70vh] overflow-hidden">
        <AiTutorPanel />
      </div>
    </div>
  );
}
